#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Pull ~/.codex/config.toml into profile base + local with smart routing.

config.base.toml に既に存在するキーは base 側の値を更新し、
それ以外（machine-local なパス・ランタイム状態など）はすべて
config.local.toml に書き出す。
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_config import emit_table  # noqa: E402


def split_runtime(
    runtime: dict[str, Any], base: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any]]:
    new_base: dict[str, Any] = {}
    new_local: dict[str, Any] = {}

    for key, base_value in base.items():
        if key not in runtime:
            new_base[key] = base_value
            continue

        runtime_value = runtime[key]
        if isinstance(base_value, dict) and isinstance(runtime_value, dict):
            sub_base, sub_local = split_runtime(runtime_value, base_value)
            new_base[key] = sub_base
            if sub_local:
                new_local[key] = sub_local
        else:
            new_base[key] = runtime_value

    for key, runtime_value in runtime.items():
        if key in base:
            continue
        new_local[key] = runtime_value

    return new_base, new_local


def render_toml(data: dict[str, Any], header_lines: list[str]) -> str:
    lines = list(header_lines)
    if header_lines:
        lines.append("")
    emit_table(lines, data, [])
    lines.append("")
    return "\n".join(lines)


def write_atomic(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            file.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def backup_if_changed(path: Path, new_content: str, timestamp: str) -> Path | None:
    if not path.exists():
        return None
    try:
        current = path.read_text(encoding="utf-8")
    except OSError:
        return None
    if current == new_content:
        return None
    backup_path = path.with_name(f"{path.name}.backup.{timestamp}")
    backup_path.write_bytes(path.read_bytes())
    try:
        os.chmod(backup_path, path.stat().st_mode & 0o777)
    except OSError:
        pass
    return backup_path


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as file:
        return tomllib.load(file)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runtime", required=True, type=Path)
    parser.add_argument("--profile-path", required=True, type=Path)
    args = parser.parse_args()

    runtime_path: Path = args.runtime
    profile_path: Path = args.profile_path
    base_path = profile_path / "config.base.toml"
    local_path = profile_path / "config.local.toml"

    if not runtime_path.is_file():
        print(f"pull_config.py: runtime config not found: {runtime_path}", file=sys.stderr)
        return 1
    if not profile_path.is_dir():
        print(f"pull_config.py: profile path not found: {profile_path}", file=sys.stderr)
        return 1

    try:
        runtime = load_toml(runtime_path)
    except Exception as error:
        print(f"pull_config.py: failed to parse {runtime_path}: {error}", file=sys.stderr)
        return 1

    base = load_toml(base_path) if base_path.is_file() else {}
    new_base, new_local = split_runtime(runtime, base)

    base_content = render_toml(new_base, [])
    local_content = render_toml(
        new_local,
        [
            "# Generated by dotfiles/codex/mise/scripts/pull_config.py.",
            "# Machine-local & runtime state imported from ~/.codex/config.toml.",
            "# Add a key to config.base.toml to promote it to a shared setting; the",
            "# next `mise run pull_config` will route the value there automatically.",
        ],
    )

    timestamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    base_backup = backup_if_changed(base_path, base_content, timestamp)
    local_backup = backup_if_changed(local_path, local_content, timestamp)

    write_atomic(base_path, base_content, mode=0o644)
    write_atomic(local_path, local_content, mode=0o600)

    if base_backup is not None:
        print(f"   base config backup: {base_path} -> {base_backup}")
    if local_backup is not None:
        print(f"   local config backup: {local_path} -> {local_backup}")

    print(f"✅ Updated {base_path}")
    print(f"✅ Updated {local_path}")
    print("   Promote new keys by adding them to config.base.toml manually.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
