#!/usr/bin/env python3
"""Render Codex config from profile-managed TOML fragments."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
import tempfile
import tomllib
from pathlib import Path
from typing import Any


BARE_KEY_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def merge_dict(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    result = dict(base)
    for key, value in override.items():
        current = result.get(key)
        if isinstance(current, dict) and isinstance(value, dict):
            result[key] = merge_dict(current, value)
        else:
            result[key] = value
    return result


def quote_key(key: str) -> str:
    if BARE_KEY_RE.match(key):
        return key
    return json.dumps(key, ensure_ascii=False)


def format_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(format_value(item) for item in value) + "]"
    if isinstance(value, dict):
        items = ", ".join(f"{quote_key(str(k))} = {format_value(v)}" for k, v in value.items())
        return "{ " + items + " }"
    if isinstance(value, (dt.datetime, dt.date, dt.time)):
        return value.isoformat()
    raise TypeError(f"Unsupported TOML value: {value!r}")


def emit_table(lines: list[str], table: dict[str, Any], path: list[str]) -> None:
    scalars: list[tuple[str, Any]] = []
    children: list[tuple[str, dict[str, Any]]] = []

    for key, value in table.items():
        if isinstance(value, dict):
            children.append((key, value))
        else:
            scalars.append((key, value))

    if path:
        if lines and lines[-1] != "":
            lines.append("")
        lines.append("[" + ".".join(quote_key(part) for part in path) + "]")

    for key, value in scalars:
        lines.append(f"{quote_key(str(key))} = {format_value(value)}")

    for key, child in children:
        emit_table(lines, child, [*path, str(key)])


def load_source(path: Path) -> dict[str, Any]:
    with path.open("rb") as file:
        data = tomllib.load(file)
    if not isinstance(data, dict):
        raise ValueError(f"{path} did not parse as a TOML table")
    return data


def find_sources(profile_path: Path) -> list[Path]:
    base = profile_path / "config.base.toml"
    legacy = profile_path / "config.toml"
    local = profile_path / "config.local.toml"

    sources: list[Path] = []
    if base.is_file():
        sources.append(base)
    elif legacy.is_file():
        sources.append(legacy)
    if local.is_file():
        sources.append(local)
    return sources


def load_profile_config(profile_path: Path) -> tuple[dict[str, Any], list[Path]]:
    sources = find_sources(profile_path)
    if not sources:
        raise FileNotFoundError(
            f"No config sources found under {profile_path}: expected config.base.toml, "
            "config.toml, or config.local.toml"
        )

    merged: dict[str, Any] = {}
    for source in sources:
        merged = merge_dict(merged, load_source(source))
    return merged, sources


def render(profile_path: Path) -> tuple[str, list[Path]]:
    merged, sources = load_profile_config(profile_path)

    lines = [
        "# Generated by dotfiles/codex/mise/scripts/render_config.py.",
        "# Persistent profile changes should go in config.base.toml or config.local.toml.",
        "# Run `mise run pull_config --prof <profile>` to import Codex-written runtime changes.",
        "",
        "# Sources:",
    ]
    lines.extend(f"# - {source}" for source in sources)
    lines.append("")
    emit_table(lines, merged, [])
    lines.append("")
    return "\n".join(lines), sources


def write_output(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as file:
            file.write(content)
        os.chmod(tmp_name, 0o600)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile-path", required=True, type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--print-sources", action="store_true")
    parser.add_argument("--same-as", type=Path)
    args = parser.parse_args()

    try:
        if args.same_as is not None:
            merged, _sources = load_profile_config(args.profile_path)
            return 0 if merged == load_source(args.same_as) else 10
        content, sources = render(args.profile_path)
    except Exception as error:
        print(f"render_config.py: {error}", file=sys.stderr)
        return 1

    if args.print_sources:
        for source in sources:
            print(source)
        return 0

    if args.output is None:
        print(content, end="")
        return 0

    write_output(args.output, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
