# markdownlint-cli2 と rumdl の両方を使用しているので、ルールセットに差異が生じないように運用すること
# rumdl と markdownlint-cli2 ではオプションに差があることがああるため、完全一致しない場合もある
# 例えば MD009 の詳細な設定である code-blocks/strict は markdownlint-cli2 にはあるが rumdl には存在しない

[global]
disable = [
  "MD013", # 行の長さは自由
  "MD014", # 標準出力がないシェルコマンドの先頭に$をつけてもよい
  "MD024", # 重複した見出しを許可
  "MD033", # インラインHTMLタグを許可
  "MD036", # 強調を見出しとして扱うことを許可
  "MD041", # ファイルの最初の行は見出しである必要はない（frontmatter が先に来るため）
  "MD060", # テーブルのパイプスタイルを許可
]

# .gitignore されているファイルを無視する
# rumdl では default で true になっているが明示的に設定しておく
respect_gitignore = true

# node_modules など自身が Markdown のフォーマットをすべきではないファイルをリンティング対象から除外する
# respect_gitignore で無視されるディレクトリはすでに除外されているが
# git管理されていない状態でも除外されるように明示的に設定しておく
exclude = [".cursor/", "node_modules/**", "worklog/**"]

[MD010]
# タブをスペースの代わりに使用することを禁じる、ただしコードブロック内は許可
spaces-per-tab = 4 # default は 4
code-blocks = false # default は false
ignore-code-languages = ["makefile"] # default は none

[MD025]
# フロントマターがある md ファイルではフロントマターと本文の見出しの重複しうるが、それで警告が出ないようにするための設定
front-matter-title = ''
