#!/usr/bin/env bash
# repo-preset: 純粋関数ライブラリ
#
# このファイルは source して使うライブラリで、直接実行しても何もしない。
# 対話 UI・実ツール実行・git 操作などの副作用は含めない
# (それらは install.sh / post_scaffold.sh 側の責務)。
#
# 使い方:
#   # shellcheck disable=SC1091
#   source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
#   rp_discover_components

# ---- COMPONENTS_DIR のデフォルト解決 ----
_RP_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${COMPONENTS_DIR:=$(cd "${_RP_LIB_DIR}/../../../repo-preset/components" && pwd)}"

# ---- コンポーネント列挙 ----

# COMPONENTS_DIR 配下のコンポーネント名(ディレクトリ名)を1行1件、ソート済みで出力する。
# HIDDEN の値に関わらず全て出力する。
rp_discover_components() {
  local d name
  for d in "${COMPONENTS_DIR}"/*/; do
    [[ -d "$d" ]] || continue
    name="$(basename "$d")"
    printf '%s\n' "$name"
  done | sort
}

# <component>/meta.sh を subshell で source し、指定フィールドの値を出力する。
# 対応フィールド: DESCRIPTION, HIDDEN
# 未定義時のデフォルト: DESCRIPTION="(no description)" / HIDDEN=0
rp_meta_field() {
  local component="$1" field="$2"
  local meta="${COMPONENTS_DIR}/${component}/meta.sh"

  (
    DESCRIPTION=""
    HIDDEN=0
    if [[ -f "$meta" ]]; then
      # shellcheck disable=SC1090
      source "$meta"
    fi
    case "$field" in
    DESCRIPTION) printf '%s\n' "${DESCRIPTION:-(no description)}" ;;
    HIDDEN) printf '%s\n' "${HIDDEN:-0}" ;;
    *)
      printf 'rp_meta_field: unknown field: %s\n' "$field" >&2
      return 1
      ;;
    esac
  )
}

# <component>/meta.sh を subshell で source し、DEPENDS_ON 配列を1行1件出力する。
# 空 (未定義) なら何も出力しない。
rp_depends_on() {
  local component="$1"
  local meta="${COMPONENTS_DIR}/${component}/meta.sh"

  (
    DEPENDS_ON=()
    if [[ -f "$meta" ]]; then
      # shellcheck disable=SC1090
      source "$meta"
    fi
    if [[ ${#DEPENDS_ON[@]} -gt 0 ]]; then
      printf '%s\n' "${DEPENDS_ON[@]}"
    fi
  )
}

# HIDDEN=1 なら真 (0) を返す。`if rp_is_hidden x; then ...` の形で使う。
rp_is_hidden() {
  local component="$1"
  local hidden
  hidden="$(rp_meta_field "$component" HIDDEN)"
  [[ "$hidden" == "1" ]]
}

# rp_discover_components から HIDDEN=1 のコンポーネントを除いた一覧を出力する。
rp_selectable_components() {
  local c
  while IFS= read -r c; do
    rp_is_hidden "$c" && continue
    printf '%s\n' "$c"
  done < <(rp_discover_components)
}

# 引数のコンポーネント群から DEPENDS_ON を BFS で推移的に辿り、閉包を求めて出力する。
# - `_common` は常に先頭に含める (_common の依存 pre-commit も引き込む)
# - 出力順序は決定的: _common を先頭固定し、以降は BFS で発見した順
#   (pre-commit は _common の DEPENDS_ON 経由で BFS の途中に発見される)
# - 存在しないコンポーネント名が来たら stderr にエラーを出し非ゼロ return
rp_resolve_closure() {
  local -a queue=() order=()
  local -A seen=()
  local c dep

  # 存在確認
  for c in "$@" _common; do
    if [[ ! -d "${COMPONENTS_DIR}/${c}" ]]; then
      printf 'rp_resolve_closure: unknown component: %s\n' "$c" >&2
      return 1
    fi
  done

  # _common を先頭固定で BFS 開始
  queue+=("_common")
  for c in "$@"; do
    [[ "$c" == "_common" ]] && continue
    queue+=("$c")
  done

  local i=0
  while ((i < ${#queue[@]})); do
    c="${queue[$i]}"
    i=$((i + 1))
    [[ -n "${seen[$c]:-}" ]] && continue
    seen[$c]=1
    order+=("$c")

    while IFS= read -r dep; do
      [[ -z "$dep" ]] && continue
      if [[ ! -d "${COMPONENTS_DIR}/${dep}" ]]; then
        printf 'rp_resolve_closure: unknown component: %s (depended on by %s)\n' "$dep" "$c" >&2
        return 1
      fi
      [[ -n "${seen[$dep]:-}" ]] && continue
      queue+=("$dep")
    done < <(rp_depends_on "$c")
  done

  printf '%s\n' "${order[@]}"
}

# ---- mise.toml 合成 ----

# 指定コンポーネント群の mise.fragment.toml から [tools] を1つに統合し、
# [tasks.*] はそのまま連結して <out_path> に書き出す。
# tools は同一キーが複数あれば後勝ちで1回だけ出す。
rp_merge_mise_toml() {
  local out="$1"
  shift
  local -a components=("$@")

  local tmp_tools tmp_rest
  tmp_tools="$(mktemp)"
  tmp_rest="$(mktemp)"
  # shellcheck disable=SC2064
  trap "rm -f '${tmp_tools}' '${tmp_rest}'" RETURN

  : >"$tmp_tools"
  : >"$tmp_rest"

  local c frag
  for c in "${components[@]}"; do
    frag="${COMPONENTS_DIR}/${c}/mise.fragment.toml"
    [[ -f "$frag" ]] || continue
    awk -v tools_out="$tmp_tools" -v rest_out="$tmp_rest" '
      BEGIN { mode="rest" }
      /^\[tools\][[:space:]]*$/ { mode="tools"; next }
      /^\[/ && !/^\[tools\]/   { mode="rest"; print >> rest_out; next }
      {
        if (mode=="tools") print >> tools_out
        else               print >> rest_out
      }
    ' "$frag"
    printf '\n' >>"$tmp_rest"
  done

  {
    printf '# Generated by repo-preset\n\n'
    if [[ -s "$tmp_tools" ]]; then
      printf '[tools]\n'
      rp__dedupe_toml_keys "$tmp_tools"
      printf '\n'
    fi
    cat "$tmp_rest"
  } >"$out"
}

# TOML の `key = value` 行を key 単位で重複除去する(後勝ち)。
# key の初出位置を保ちつつ、値は最後に出現した行のものを採用する。
# 空行/コメント行はそのまま順序維持で出力する。
rp__dedupe_toml_keys() {
  local file="$1"
  awk '
    function trim(s) { gsub(/^[[:space:]]+|[[:space:]]+$/, "", s); return s }
    /^[[:space:]]*#/ || /^[[:space:]]*$/ {
      seq++
      kind[seq] = "raw"
      raw[seq] = $0
      next
    }
    {
      eq = index($0, "=")
      key = trim(substr($0, 1, eq - 1))
      if (!(key in first_seq)) {
        seq++
        first_seq[key] = seq
        kind[seq] = "kv"
      }
      value[key] = $0
      order[first_seq[key]] = key
    }
    END {
      for (i = 1; i <= seq; i++) {
        if (kind[i] == "raw") print raw[i]
        else if (kind[i] == "kv") print value[order[i]]
      }
    }
  ' "$file"
}

# ---- 集約タスク生成 ----

# 選択コンポーネントの mise.fragment.toml から `<領域>:lint` `<領域>:fix`/`<領域>:format` を
# 持つものを走査し、[tasks.lint] / [tasks.fix] の depends 配列を TOML 断片として出力する。
rp_generate_aggregate_tasks() {
  local -a components=("$@")
  local -a lint_tasks=() fix_tasks=()
  local c frag task

  for c in "${components[@]}"; do
    frag="${COMPONENTS_DIR}/${c}/mise.fragment.toml"
    [[ -f "$frag" ]] || continue
    while IFS= read -r task; do
      [[ -z "$task" ]] && continue
      case "$task" in
      *:lint) lint_tasks+=("$task") ;;
      *:fix | *:format) fix_tasks+=("$task") ;;
      esac
    done < <(grep -oE '^\[tasks\."[^"]+"\]' "$frag" | sed -E 's/^\[tasks\."([^"]+)"\]$/\1/')
  done

  if [[ ${#lint_tasks[@]} -gt 0 ]]; then
    printf '[tasks.lint]\n'
    printf 'description = "全領域の lint を実行"\n'
    printf 'depends = [%s]\n\n' "$(rp__quote_csv "${lint_tasks[@]}")"
  fi

  if [[ ${#fix_tasks[@]} -gt 0 ]]; then
    printf '[tasks.fix]\n'
    printf 'description = "全領域の自動整形/修正を実行"\n'
    printf 'depends = [%s]\n\n' "$(rp__quote_csv "${fix_tasks[@]}")"
  fi
}

# 引数を `"a", "b"` 形式にする。
rp__quote_csv() {
  local -a items=("$@")
  local out="" item
  for item in "${items[@]}"; do
    if [[ -n "$out" ]]; then
      out+=", "
    fi
    out+="\"${item}\""
  done
  printf '%s' "$out"
}

# ---- ファイルコピー ----

# コンポーネントディレクトリ内のファイルを target にコピーする。
# meta.sh / mise.fragment.toml / *.gitignore.append / post_scaffold.sh /
# dependabot.fragment.yml / pyproject.overlay.toml はコピー対象から除外する。
# --dry-run 指定時はコピーせず、コピー予定パスを "  + <relpath>" 形式で出力する。
rp_copy_component() {
  local component="$1" target_dir="$2" dry_run=0
  if [[ "${3:-}" == "--dry-run" ]]; then
    dry_run=1
  fi

  local src="${COMPONENTS_DIR}/${component}"
  if [[ ! -d "$src" ]]; then
    printf 'rp_copy_component: component not found: %s\n' "$component" >&2
    return 1
  fi

  local file rel
  while IFS= read -r -d '' file; do
    rel="${file#"${src}/"}"
    case "$rel" in
    mise.fragment.toml | meta.sh | *.gitignore.append | post_scaffold.sh | dependabot.fragment.yml | pyproject.overlay.toml)
      continue
      ;;
    esac
    if ((dry_run)); then
      printf '  + %s\n' "$rel"
    else
      mkdir -p "$(dirname "${target_dir}/${rel}")"
      cp "$file" "${target_dir}/${rel}"
    fi
  done < <(find "$src" -type f -print0 | sort -z)
}

# ---- プレースホルダ置換 ----

# target_dir 配下の *.md *.toml *.json *.jsonc *.yml *.yaml CODEOWNERS に対し、
# {{project_name}} {{project_slug}} {{github_user}} を置換する。
rp_substitute_placeholders() {
  local target_dir="$1" project_name="$2" project_slug="$3" github_user="$4"

  local -a targets=()
  while IFS= read -r -d '' f; do
    targets+=("$f")
  done < <(
    find "$target_dir" \
      \( -path '*/node_modules/*' -o -path '*/.venv/*' -o -path '*/.git/*' \) -prune -o \
      -type f \
      \( -name '*.md' -o -name '*.toml' -o -name '*.json' -o -name '*.jsonc' \
      -o -name '*.yml' -o -name '*.yaml' -o -name 'CODEOWNERS' \) -print0
  )

  [[ ${#targets[@]} -eq 0 ]] && return 0

  if command -v perl >/dev/null 2>&1; then
    PROJECT_NAME="$project_name" \
      PROJECT_SLUG="$project_slug" \
      GITHUB_USER="$github_user" \
      perl -i -pe '
        s/\{\{project_name\}\}/$ENV{PROJECT_NAME}/g;
        s/\{\{project_slug\}\}/$ENV{PROJECT_SLUG}/g;
        s/\{\{github_user\}\}/$ENV{GITHUB_USER}/g;
      ' "${targets[@]}"
  else
    local f tmp
    for f in "${targets[@]}"; do
      tmp="$(mktemp)"
      sed \
        -e "s/{{project_name}}/${project_name}/g" \
        -e "s/{{project_slug}}/${project_slug}/g" \
        -e "s/{{github_user}}/${github_user}/g" \
        "$f" >"$tmp"
      mv "$tmp" "$f"
    done
  fi
}

# ---- .gitignore 合成 ----

# _common/.gitignore を基底に、各コンポーネントの .gitignore.append があれば
# マーカー付きで連結して out に書く。
rp_merge_gitignore() {
  local base_gitignore="$1" out="$2"
  shift 2
  local -a components=("$@")

  {
    cat "$base_gitignore"
    local c f
    for c in "${components[@]}"; do
      f="${COMPONENTS_DIR}/${c}/.gitignore.append"
      if [[ -f "$f" ]]; then
        printf '\n# === repo-preset: %s ===\n' "$c"
        cat "$f"
      fi
    done
  } >"$out"
}

# ---- dependabot.yml 合成 ----

# github/.github/dependabot.yml (基底) をベースに、選択コンポーネントの
# dependabot.fragment.yml の updates エントリを追記合成する。
# 基底に既に含まれる github 自身の fragment は二重に足さない。
rp_compose_dependabot() {
  local out="$1" base_dependabot="$2"
  shift 2
  local -a components=("$@")

  local base_entries
  base_entries="$(awk '/^updates:[[:space:]]*$/{flag=1; next} flag' "$base_dependabot")"

  {
    printf 'version: 2\n\n'
    printf 'updates:\n'
    printf '%s\n' "$base_entries"
    local c f
    for c in "${components[@]}"; do
      [[ "$c" == "github" ]] && continue
      f="${COMPONENTS_DIR}/${c}/dependabot.fragment.yml"
      [[ -f "$f" ]] || continue
      grep -v '^# fragment:' "$f"
    done
  } >"$out"
}

# ファイル末尾の連続する空行を取り除き、末尾を単一改行に正規化する。
# fragment 連結で生じる余分な末尾空行が taplo fmt などの整形チェックで
# 差分として検出されるのを防ぐ。
rp_trim_trailing_blank_lines() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  local tmp
  tmp="$(mktemp)"
  # 最後に内容を持つ行までを出力し、それ以降の末尾空行を捨てる。
  # awk は行を溜めず、非空行が来た時点で保留していた空行ごと吐き出す。
  awk '
    /[^[:space:]]/ { for (i = 0; i < pending; i++) print ""; pending = 0; print; next }
    { pending++ }
  ' "$file" >"$tmp"
  mv "$tmp" "$file"
}

# ---- source ガード ----
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  printf 'lib.sh は source して使うライブラリです。直接実行できません。\n' >&2
  printf '使い方: source "%s"\n' "${BASH_SOURCE[0]}" >&2
  exit 1
fi
