[tool.poetry]
name = "my-utils"
version = "0.1.0"
description = ""
readme = "README.md"
authors = []
packages = [{ include = "my_utils" }]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
