windows_wsl_setup_acknowledged = true
model = "gpt-5-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

[projects.'\\?\C:\Users\S13316\dotfiles']
trust_level = "trusted"
