windows_wsl_setup_acknowledged = true
model = "gpt-5-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

notify = [
  "pwsh.exe",
  "-NoLogo",
  "-ExecutionPolicy",
  "Bypass",
  "-STA",
  "-File",
  "C:/Users/S13316/dotfiles/codex/profiles/win-15034/notify.ps1",
]

[tools]
web_search = true

[mcp_servers.serena]
command = "C:\\Users\\S13316\\scoop\\shims\\uvx.exe"
startup_timeout_sec = 60
args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "codex",
]

[mcp_servers.serena.env]
APPDATA = "C:\\Users\\S13316\\AppData\\Roaming"
LOCALAPPDATA = "C:\\Users\\S13316\\AppData\\Local"
SYSTEMROOT = "C:\\Windows"
SYSTEMDRIVE = "C:"
PROGRAMDATA = "C:\\ProgramData"
PROGRAMFILES = "C:\\Program Files"
"PROGRAMFILES(X86)" = "C:\\Program Files (x86)"
HOMEDRIVE = "C:"
HOMEPATH = "\\Users\\S13316"
HOME = "C:\\Users\\S13316"
USERPROFILE = "C:\\Users\\S13316"
COMSPEC = "C:\\Windows\\System32\\cmd.exe"

[projects.'\\?\C:\Users\S13316\dotfiles']
trust_level = "trusted"

[projects.'\\?\C:\Users\S13316\programs\server_task\cyg-sercuit\collection']
trust_level = "trusted"

[projects.'\\?\C:\Users\S13316\programs\akasha']
trust_level = "trusted"

[projects.'\\?\C:\Users\S13316\programs\ai-tech\ip-bridge']
trust_level = "trusted"
