model = "gpt-5-codex"
model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true

notify = [
  "env",
  "CODEX_NOTIFY_DEBUG_LOG=/Users/s13316/dotfiles/codex/profiles/cg-m2-mac/notify.log",
  "/bin/bash",
  "-c",
  "/Users/s13316/dotfiles/codex/profiles/cg-m2-mac/notify.sh",
]

#　デスクトップ通知に関する設定
# - "agent-turn-complete": エージェントの１ターン処理が完了した際に通知
# - "approval-requested": ユーザーの操作や承認が必要な時に通知
[tui]
notifications = ["agent-turn-complete", "approval-requested"]

[tools]
web_search = true

[mcp_servers.serena]
command = "uvx"
startup_timeout_sec = 60
args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "codex",
]

[projects."/Users/s13316/dotfiles"]
trust_level = "trusted"

[projects."/Users/s13316"]
trust_level = "trusted"
